administration_route_choices = [
    ("PO", "By Mouth"),
    ("IV", "Intravenous"),
    ("IM", "Intramuscular"),
    ("SC", "Subcutaneous"),
    ("PR", "Per Rectum"),
    ("SL", "Sublingual"),
    ("TD", "Transdermal"),
    ("INH", "Inhalation"),
    ("OTH", "Other"),
]


administration_frequency_choices = [
    ("QD", "Once Daily"),
    ("BID", "Twice Daily"),
    ("TID", "Three Times Daily"),
    ("QID", "Four Times Daily"),
    ("Q4H", "Every 4 Hours"),
    ("Q6H", "Every 6 Hours"),
    ("Q8H", "Every 8 Hours"),
    ("Q12H", "Every 12 Hours"),
    ("QAM", "Every Morning"),
    ("QPM", "Every Evening"),
    ("QWK", "Once Weekly"),
    ("Q2WK", "Every 2 Weeks"),
    ("QMO", "Once Monthly"),
    ("Q3MO", "Every 3 Months"),
    ("Q6MO", "Every 6 Months"),
    ("QYR", "Once Yearly"),
    ("PRN", "As Needed"),
    ("OTH", "Other"),
]

dosage_form_choices = [
    ("TAB", "Tablet"),
    ("CAP", "Capsule"),
    ("LIQ", "Liquid"),
    ("INJ", "Injection"),
    ("SUP", "Suppository"),
    ("LOT", "Lotion"),
    ("CRM", "Cream"),
    ("OIN", "Ointment"),
    ("SLN", "Solution"),
    ("GEL", "Gel"),
    ("PCH", "Patch"),
    ("DSC", "Disc"),
    ("PUL", "Pulvule"),
    ("SUS", "Suspension"),
    ("SYR", "Syrup"),
    ("DRO", "Drops"),
    ("INH", "Inhaler"),
    ("OTH", "Other"),
]
