# Generated by Django 3.2.11 on 2023-11-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication_adherence_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
